In [1]:
# Load data
import pandas as pd
pd.set_option('display.max_columns', 100)
train = pd.read_csv("../data/interim/train.csv")
dev = pd.read_csv("../data/interim/dev.csv")
test = pd.read_csv("../data/interim/test.csv")
df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
assert df.shape[0] == train.shape[0] + dev.shape[0] + test.shape[0]
train.shape, dev.shape, test.shape, df.shape

((4225, 31), (1409, 31), (1409, 31), (7043, 21))

In [2]:
# Same ratio of target values
print(" ", train['churn'].value_counts(normalize=True).values, "\n ", \
      dev['churn'].value_counts(normalize=True).values, "\n ", \
      test['churn'].value_counts(normalize=True).values)

  [0.73467456 0.26532544]
  [0.73456352 0.26543648]
  [0.73456352 0.26543648]

In [3]:
train.head()

,senior_citizen,tenure,monthly_charges,total_charges,churn,is_female,has_partner,has_dependents,has_phone_service,multiple_lines__yes,multiple_lines__no_phone_service,internet_service__fiber_optic,internet_service__dsl,online_security__yes,online_security__no_internet_service,online_backup__yes,online_backup__no_internet_service,device_protection__yes,device_protection__no_internet_service,tech_support__yes,tech_support__no_internet_service,streaming_tv__yes,streaming_tv__no_internet_service,streaming_movies__yes,streaming_movies__no_internet_service,contract__month_to_month,contract__two_year,has_paperless_billing,payment_method__electronic_check,payment_method__mailed_check,payment_method__bank_transfer_automatic
0,1,67,54.90,3725.50,0,1,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
1,0,23,93.50,2341.55,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,0,0
2,0,64,92.85,5980.75,0,1,1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0
3,0,72,24.15,1776.45,0,1,1,0,1,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0
4,0,56,24.30,1261.70,0,1,1,0,1,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0

In [4]:
for column in train.columns:
    print("-------", column, "-------\n", train[column].value_counts(), "\n", "-"*(len(column)+15), "\n")

------- senior_citizen -------
 0    3507
1     718
Name: senior_citizen, dtype: int64
 -----------------------------

------- tenure -------
 1     356
72    231
2     137
3     127
71    105
4     104
5      78
10     77
7      73
12     72
6      71
9      69
70     69
8      65
68     63
11     62
18     61
66     60
67     60
13     60
15     58
23     58
16     56
17     53
22     52
69     52
35     52
24     51
56     51
61     49
     ...
37     42
14     42
55     42
21     42
64     41
40     41
29     41
30     41
63     40
45     40
51     40
20     40
49     39
62     39
48     39
53     38
58     38
34     37
33     37
59     37
42     37
28     37
43     36
38     35
32     35
31     34
39     33
36     30
44     28
0       6
Name: tenure, Length: 73, dtype: int64
 ---------------------

------- monthly_charges -------
 20.05     41
20.00     32
19.85     28
19.70     28
19.65     27
19.90     27
19.75     27
19.80     25
20.25     25
20.20     24
20.15     24
20.10     23
19.55     23
19.50     22
20.35     22
19.95     20
20.50     20
20.30     20
19.60     19
19.35     18
20.45     17
20.40     17
19.30     16
19.40     16
19.45     15
25.10     14
70.15     13
19.25     13
20.65     12
79.85     11
          ..
26.35      1
77.20      1
107.55     1
36.45      1
104.20     1
40.45      1
113.10     1
46.10      1
77.55      1
102.70     1
92.10      1
112.10     1
103.80     1
111.40     1
111.75     1
88.10      1
34.65      1
103.60     1
72.10      1
107.25     1
36.05      1
65.75      1
52.20      1
39.85      1
46.60      1
37.70      1
116.80     1
86.75      1
106.25     1
68.15      1
Name: monthly_charges, Length: 1377, dtype: int64
 ------------------------------

------- total_charges -------
 20.20      7
20.05      6
19.75      6
19.65      4
19.55      4
50.15      4
20.30      4
45.30      4
20.50      4
69.60      4
70.15      3
20.35      3
84.50      3
19.30      3
79.55      3
470.20     3
19.40      3
69.90      3
19.90      3
25.25      3
19.50      3
70.10      3
45.70      3
20.25      3
70.60      3
20.40      3
69.10      3
85.45      2
193.60     2
214.75     2
          ..
3775.85    1
3024.15    1
255.50     1
1580.10    1
6725.50    1
3541.40    1
2460.55    1
1423.05    1
84.65      1
1468.90    1
403.35     1
7843.55    1
6396.45    1
74.25      1
1415.00    1
156.25     1
108.95     1
198.50     1
749.25     1
625.05     1
533.60     1
921.55     1
8058.85    1
5893.15    1
4154.55    1
5825.50    1
296.10     1
279.20     1
7623.20    1
228.00     1
Name: total_charges, Length: 4018, dtype: int64
 ----------------------------

------- churn -------
 0    3104
1    1121
Name: churn, dtype: int64
 --------------------

------- is_female -------
 0    2151
1    2074
Name: is_female, dtype: int64
 ------------------------

------- has_partner -------
 0    2180
1    2045
Name: has_partner, dtype: int64
 --------------------------

------- has_dependents -------
 0    2974
1    1251
Name: has_dependents, dtype: int64
 -----------------------------

------- has_phone_service -------
 1    3834
0     391
Name: has_phone_service, dtype: int64
 --------------------------------

------- multiple_lines__yes -------
 0    2418
1    1807
Name: multiple_lines__yes, dtype: int64
 ----------------------------------

------- multiple_lines__no_phone_service -------
 0    3834
1     391
Name: multiple_lines__no_phone_service, dtype: int64
 -----------------------------------------------

------- internet_service__fiber_optic -------
 0    2335
1    1890
Name: internet_service__fiber_optic, dtype: int64
 --------------------------------------------

------- internet_service__dsl -------
 0    2808
1    1417
Name: internet_service__dsl, dtype: int64
 ------------------------------------

------- online_security__yes -------
 0    3032
1    1193
Name: online_security__yes, dtype: int64
 -----------------------------------

------- online_security__no_internet_service -------
 0    3307
1     918
Name: online_security__no_internet_service, dtype: int64
 ---------------------------------------------------

------- online_backup__yes -------
 0    2769
1    1456
Name: online_backup__yes, dtype: int64
 ---------------------------------

------- online_backup__no_internet_service -------
 0    3307
1     918
Name: online_backup__no_internet_service, dtype: int64
 -------------------------------------------------

------- device_protection__yes -------
 0    2779
1    1446
Name: device_protection__yes, dtype: int64
 -------------------------------------

------- device_protection__no_internet_service -------
 0    3307
1     918
Name: device_protection__no_internet_service, dtype: int64
 -----------------------------------------------------

------- tech_support__yes -------
 0    3019
1    1206
Name: tech_support__yes, dtype: int64
 --------------------------------

------- tech_support__no_internet_service -------
 0    3307
1     918
Name: tech_support__no_internet_service, dtype: int64
 ------------------------------------------------

------- streaming_tv__yes -------
 0    2579
1    1646
Name: streaming_tv__yes, dtype: int64
 --------------------------------

------- streaming_tv__no_internet_service -------
 0    3307
1     918
Name: streaming_tv__no_internet_service, dtype: int64
 ------------------------------------------------

------- streaming_movies__yes -------
 0    2579
1    1646
Name: streaming_movies__yes, dtype: int64
 ------------------------------------

------- streaming_movies__no_internet_service -------
 0    3307
1     918
Name: streaming_movies__no_internet_service, dtype: int64
 ----------------------------------------------------

------- contract__month_to_month -------
 1    2336
0    1889
Name: contract__month_to_month, dtype: int64
 ---------------------------------------

------- contract__two_year -------
 0    3212
1    1013
Name: contract__two_year, dtype: int64
 ---------------------------------

------- has_paperless_billing -------
 1    2535
0    1690
Name: has_paperless_billing, dtype: int64
 ------------------------------------

------- payment_method__electronic_check -------
 0    2816
1    1409
Name: payment_method__electronic_check, dtype: int64
 -----------------------------------------------

------- payment_method__mailed_check -------
 0    3242
1     983
Name: payment_method__mailed_check, dtype: int64
 -------------------------------------------

------- payment_method__bank_transfer_automatic -------
 0    3296
1     929
Name: payment_method__bank_transfer_automatic, dtype: int64
 ------------------------------------------------------

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4225 entries, 0 to 4224
Data columns (total 31 columns):
senior_citizen                             4225 non-null int64
tenure                                     4225 non-null int64
monthly_charges                            4225 non-null float64
total_charges                              4219 non-null float64
churn                                      4225 non-null int64
is_female                                  4225 non-null int64
has_partner                                4225 non-null int64
has_dependents                             4225 non-null int64
has_phone_service                          4225 non-null int64
multiple_lines__yes                        4225 non-null int64
multiple_lines__no_phone_service           4225 non-null int64
internet_service__fiber_optic              4225 non-null int64
internet_service__dsl                      4225 non-null int64
online_security__yes                       4225 non-null int64
online_security__no_internet_service       4225 non-null int64
online_backup__yes                         4225 non-null int64
online_backup__no_internet_service         4225 non-null int64
device_protection__yes                     4225 non-null int64
device_protection__no_internet_service     4225 non-null int64
tech_support__yes                          4225 non-null int64
tech_support__no_internet_service          4225 non-null int64
streaming_tv__yes                          4225 non-null int64
streaming_tv__no_internet_service          4225 non-null int64
streaming_movies__yes                      4225 non-null int64
streaming_movies__no_internet_service      4225 non-null int64
contract__month_to_month                   4225 non-null int64
contract__two_year                         4225 non-null int64
has_paperless_billing                      4225 non-null int64
payment_method__electronic_check           4225 non-null int64
payment_method__mailed_check               4225 non-null int64
payment_method__bank_transfer_automatic    4225 non-null int64
dtypes: float64(2), int64(29)
memory usage: 1023.3 KB

In [10]:
dev['senior_citizen'].value_counts()

0    1191
1     218
Name: senior_citizen, dtype: int64

In [11]:
train.columns

Index(['senior_citizen', 'tenure', 'monthly_charges', 'total_charges', 'churn',
       'is_female', 'has_partner', 'has_dependents', 'has_phone_service',
       'multiple_lines__yes', 'multiple_lines__no_phone_service',
       'internet_service__fiber_optic', 'internet_service__dsl',
       'online_security__yes', 'online_security__no_internet_service',
       'online_backup__yes', 'online_backup__no_internet_service',
       'device_protection__yes', 'device_protection__no_internet_service',
       'tech_support__yes', 'tech_support__no_internet_service',
       'streaming_tv__yes', 'streaming_tv__no_internet_service',
       'streaming_movies__yes', 'streaming_movies__no_internet_service',
       'contract__month_to_month', 'contract__two_year',
       'has_paperless_billing', 'payment_method__electronic_check',
       'payment_method__mailed_check',
       'payment_method__bank_transfer_automatic'],
      dtype='object')